---
micronaut:
  application:
    name: api-swagger
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2


---
micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
        path: /authenticate
      oauth:
        enabled: true
    token:
      basic-auth:
        enabled: false
      jwt:
        enabled: true
        roles-name: ROLE_USER
        signatures:
          secret:
            generator:
              secret: pleaseChangeThisSecretForANewOne
    intercept-url-map:
      - pattern: /swagger/**
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        access:
          - isAnonymous()
